#git show ac0c0d9:thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/FrmSampleClient.cs
git show $1:thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/FrmSampleClient.cs
