git add README.md
git add Truck_Project1_notes.txt
git add gitadd.sh
git add .gitignore

git add Truck_App1/Truck_App1.xise
git add Truck_App1/Truck_App.ucf
git add Truck_App1/Truck_App1.vhd
git add Truck_App1/Frequency.vhd
git add Truck_App1/period.vhd
git add Truck_App1/mod_m.vhd
git add Truck_App1/div.vhd
git add Truck_App1/bcd.vhd
git add Truck_App1/debounce.vhd
git add Truck_App1/3S500E_layout_bottom.txt
git add Truck_App1/3S500E_pin_assign.ods
git add Truck_App1/uartLED.vhd
git add Truck_App1/sendcharLED.vhd
git add Truck_App1/uartLED.vhd
git add Truck_App1/uartLED2.vhd
git add Truck_App1/uart_tx.vhd
git add Truck_App1/uart_rx.vhd
git add Truck_App1/setdecimalLED.vhd
git add Truck_App1/board_layout.txt
git add Truck_App1/rpm.ods
git add Truck_App1/sensor.vhd
git add Truck_App1/wrapperLED.vhd
git add Truck_App1/spi_slave.vhd
git add Truck_App1/spi_master.vhd
git add Truck_App1/test_uart/test_uart.vhd
git add Truck_App1/test_uart/test_uart.xise
git add Truck_App1/test_uart/test_uart.ucf
git add Truck_App1/test_rpm_mph.c
git add Truck_App1/test_write.c
git add Truck_App1/lib/*

git add PIC24_support/lib/*
git add PIC24_support/esos/*
git add PIC24_support/esos1/Truck_App2.c
git add PIC24_support/esos1/Truck_App.h
git add PIC24_support/esos1/ESOS1.X/nbproject
git add PIC24_support/esos1/ESOS1.X/Makefile
git add PIC24_support/PIC24FJ_pinlist.ods
git add PIC24_support/PIC24_board_pinout.txt

git add thread_io/getadd.sh
git add thread_io/ioports.c
git add thread_io/Makefile
git add thread_io/sched.c
git add thread_io/ioports.h
git add thread_io/test_ioports.c
git add thread_io/tasks.c
git add thread_io/tasks.h
git add thread_io/queue/rdwr.h
git add thread_io/queue/rdwr.c
git add thread_io/queue/illist_threads_rw.h
git add thread_io/queue/illist_threads_rw.c
git add thread_io/queue/ollist_threads_rw.h
git add thread_io/queue/ollist_threads_rw.c
git add thread_io/ncurses/client.c
git add thread_io/ncurses/client.h
git add thread_io/linux_make
git add thread_io/serial_io.c
git add thread_io/serial_io.h
git add thread_io/mytypes.h
git add thread_io/ncurses/comp_forms.sh
git add thread_io/ncurses/demo_forms2.c
git add thread_io/ncurses/demo_menus2.c
git add thread_io/ncurses/edit_field2.c
git add thread_io/ncurses/edit_field.h
git add thread_io/ncurses/menu_scroll2.c
git add thread_io/ncurses/Makefile
git add thread_io/ncurses/init_db.c
git add thread_io/ncurses/list_db.c
git add thread_io/ncurses/setiodata.h
git add thread_io/ncurses/tcp_win.c
git add thread_io/ncurses/config_file.c
git add thread_io/ncurses/file_win.c
git add thread_io/ncurses/file_menu2.c
git add thread_io/ncurses/demo_forms4.c
git add thread_io/ncurses/form_supplement.c
git add thread_io/ncurses/form_sup.h
git add thread_io/ncurses/forms.sh
git add thread_io/ncurses/test.priv.h

git add AVR_t6963/atmega328p.conf
git add AVR_t6963/avrdude.conf
git add AVR_t6963/dobus2
git add AVR_t6963/getinfo
git add AVR_t6963/gitadd.sh
git add AVR_t6963/Makefile
git add AVR_t6963/run-avrdude
git add AVR_t6963/ProMiniPinout.txt
git add AVR_t6963/sfr_helper.h
git add AVR_t6963/USART.c
git add AVR_t6963/USART.h
git add AVR_t6963/portpins.h
git add AVR_t6963/pinDefines.h
git add AVR_t6963/macros.h
git add AVR_t6963/binaryMacro.h
git add AVR_t6963/t6963.h
git add AVR_t6963/t6963.c
git add AVR_t6963/AVR_menu.c
git add AVR_t6963/PIC_menu.c
git add AVR_t6963/main.c
git add AVR_t6963/pic_main.h
git add AVR_t6963/avr_main.h
git add AVR_t6963/main.h
git add AVR_t6963/spi.c
git add AVR_t6963/spi.h
git add AVR_t6963/supp.c
git add AVR_t6963/ERM240128.png
git add AVR_t6963/test_write_data/sim_read.c
git add AVR_t6963/test_write_data/sim_write.c
git add AVR_t6963/test_write_data/make_avr
git add AVR_t6963/test_write_data/make_pic
git add AVR_t6963/test_write_data/copy1.sh
git add AVR_t6963/test_write_data/copy2.sh
git add AVR_t6963/test_write_data/domake1
git add AVR_t6963/test_write_data/domake2
git add AVR_t6963/test_write_data/read_eeprom_sim.c
git add AVR_t6963/test_write_data/read_eeprom_sim2.c
git add AVR_t6963/test_write_data/make_show_eeprom
clear
git status
git log --oneline > oneline.txt
#git log | grep Date
