git add README.md
git add Truck_Project1_notes.txt
git add main_box.txt
git add io_box.txt
git add gitadd.sh
git add .gitignore
git add mytypes.h
git add gitstatus.sh
git add engine_startup_notes.txt
git add alot_of_work.txt
git add append_br.c
git add replace_tabs.c
git add avr_cmds.txt
git add main_box_pinout.ods
git add avr_menus.txt
git add todo_bug_list.txt
git add client_server_notes.odt
git add Images/SystemDiagram.JPG
git add Images/ClientUI.JPG
git add Images/ClientUI2.JPG
git add Images/STM32pinout.JPG
git add Images/DlgSetParams.JPG
git add Images/iobox.JPG

git add STM32/*
git add STM32/.cproject
git add STM32/.mxproject
git add STM32/*.ioc

git add AVR_t6963/atmega328p.conf
git add AVR_t6963/do1.sh
git add AVR_t6963/Makefile
git add AVR_t6963/ProMiniPinout.txt
git add AVR_t6963/spi.c
git add AVR_t6963/t6963.h
git add AVR_t6963/avrdude.conf
git add AVR_t6963/macros.h
git add AVR_t6963/pinDefines.h
git add AVR_t6963/run-avrdude
git add AVR_t6963/spi.h
git add AVR_t6963/USART.c
git add AVR_t6963/main.c
git add AVR_t6963/portpins.h
git add AVR_t6963/sfr_helper.h
git add AVR_t6963/t6963.c
git add AVR_t6963/USART.h
git add AVR_t6963/test_gdisp.cx

git add AVR_t6963/eeprom/main_burn.c
git add AVR_t6963/eeprom/t6963.c
git add AVR_t6963/eeprom/t6963.h
git add AVR_t6963/eeprom/test.cx

git add AVR_t6963/test/dmake3
git add AVR_t6963/test/main.c
git add AVR_t6963/test/make_target2
git add AVR_t6963/test/readme.txt

git add Truck_App1/Multi-Byte.vhd
git add Truck_App1/multi-byte.ucf
git add Truck_App1/multi-byte.xise
git add Truck_App1/Frequency.vhd
git add Truck_App1/period.vhd
git add Truck_App1/mod_m.vhd
git add Truck_App1/div.vhd
git add Truck_App1/pwm2.vhd
git add Truck_App1/debounce.vhd
git add Truck_App1/3S500E_layout_bottom.txt
git add Truck_App1/3S500E_pin_assign.ods
git add Truck_App1/uartLED.vhd
git add Truck_App1/uartLED2.vhd
git add Truck_App1/uart_tx.vhd
git add Truck_App1/uart_rx.vhd
git add Truck_App1/rpm.ods
git add Truck_App1/sensor.vhd
git add Truck_App1/dtmf.vhd
git add Truck_App1/lcd_pwm.vhd
git add Truck_App1/lib/Common.vhd

git add thread_io/setARMpath.sh
git add thread_io/ioports.c
git add thread_io/Makefile
git add thread_io/sched.c
git add thread_io/ioports.h
git add thread_io/tasks.c
git add thread_io/cmd_tasks.c
git add thread_io/tasks.h
git add thread_io/lcd_func.c
git add thread_io/lcd_func.h
git add thread_io/queue/rdwr.h
git add thread_io/queue/rdwr.c
git add thread_io/queue/ollist_threads_rw.h
git add thread_io/queue/ollist_threads_rw.c
git add thread_io/linux_make
git add thread_io/make_db
git add thread_io/serial_io.c
git add thread_io/serial_io.h
git add thread_io/read_sd.c
git add thread_io/thread_io_notes.txt
git add thread_io/mingetty/mountcf.sh
git add thread_io/mingetty/try_sched_7250.sh
git add thread_io/mingetty/inittab
git add thread_io/mingetty/mingetty
git add thread_io/mingetty/my_startup.sh
git add thread_io/mingetty/try_sched.sh
git add thread_io/mingetty/inittab_TS-7200
git add thread_io/mingetty/mingetty.c
git add thread_io/mingetty/Makefile
git add thread_io/mingetty/param.conf
git add thread_io/test_tcp/*.c
git add thread_io/test_tcp/*.h
git add thread_io/test_tcp/iostate.bin
git add thread_io/test_tcp/make_target
git add thread_io/test_tcp/Makefile
git add thread_io/test_tcp/Makefile2
git add thread_io/ir104_man.pdf
git add thread_io/how2formatSDCardExt.png
git add thread_io/TS-7200_connections.jpg
git add thread_io/manage_boot_bios.txt
git add thread_io/shell2linux.txt
git add thread_io/IO_card_layout.png
git add thread_io/print_cmds.c
git add thread_io/do_print_cmds.sh
git add thread_io/cmds_list.txt
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/ChildDialog.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/ClientParams.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EngTempLimit.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/FanOffTemp.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/FanOnTemp.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/player.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat1.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat2.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat3.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/BattBoxTemp.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/Blower1Temps.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/Blower2Temps.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/Blower3Temps.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/BlowerEnTemps.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/HighRevLimit.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/LightsOnDelay.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/LowRevLimit.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat4.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat5.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/uiformat6.xml
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer.sln
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Settings.settings
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Settings.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Resources.resx
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Resources.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/AssemblyInfo.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Properties/Resources.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Properties/Resources.resx
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Properties/Settings.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Properties/Settings.settings
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/EpServerEngineSampleClient.csproj
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ChildDialogs.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Child_Scrolling_List.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Child_Scrolling_List.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ClientParams.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/_Client_SQL_DB2DataSet1.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/_Client_SQL_DB2DataSet.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ConfigParams.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/DlgForm1.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/DlgForm1.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/DlgSetParams.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/DlgSetParams.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/FrmSampleClient.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/FrmSampleClient.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/PlayerDlg.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/PlayerDlg.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/PortSet2.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/PortSet2.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/Program.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ServerCmds.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/SListTypes.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/SwitchTable.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/SwitchTable.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/UIFormat.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ManageServer.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ManageServer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/ManageServer.resx
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/ClientSide/ClientInterface.cs
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/EpServerEngine.cs.csproj
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient.sln
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/App.config
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/SQLQuery2.sql

git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer.sln
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Settings.settings
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Settings.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Resources.resx
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/Resources.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Properties/AssemblyInfo.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/EpServerEngineSampleServer.csproj
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/Program.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/App.config
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/FrmSampleServer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/FrmSampleServer.resx
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/FrmSampleServer.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/ParamsForm.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/ParamsForm.resx
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/ParamsForm.Designer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/ConfigParams.cs
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleServer/EpServerEngineSampleServer/ServerCmds.cs

git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/IocpTcpServer.cs
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/IocpTcpSocket.cs
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/Room.cs
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/RoomInterface.cs
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/ServerInterface.cs
git add thread_io/cs_client/EpServerClient/EpServerEngine.cs/EpServerEngine.cs/bin/
git add thread_io/cs_client/EpServerClient/EpServerEngineSampleClient/EpServerEngineSampleClient/EpServerEngineSampleClient.csproj.user

git add thread_io/cs_client/server_on_linux.c
git add thread_io/cs_client/server_on_linux2.c
git add thread_io/cs_client/new_client.txt
git add thread_io/cs_client/init_db.c
git add thread_io/cs_client/list_db.c
git add thread_io/cs_client/list_db2.c
git add thread_io/cs_client/make_db
git add thread_io/cs_client/make_db2
git add thread_io/cs_client/config_file.c
git add thread_io/cs_client/config_file.h
git add thread_io/odata.csv
git add SendFiles/*

git add XMEGA/avr_compiler.h
git add XMEGA/documentation.h
git add XMEGA/Makefile
git add XMEGA/TC_driver.h
git add XMEGA/usart_driver.c
git add XMEGA/clean.sh
git add XMEGA/main.c
git add XMEGA/TC_driver.c
git add XMEGA/usart_compile.sh
git add XMEGA/usart_driver.h

./gitstatus.sh



