git add README.md
git add Truck_Project1_notes.txt
git add super_truck_notes.txt
git add monster_box.txt
git add HDM128GS24L.png
git add IPC_layout.png
git add MT-DB-X4_pinout.png
git add todo.txt
git add gitadd.sh
git add .gitignore

git add AVR_t6963/atmega328p.conf
git add AVR_t6963/do1.sh
git add AVR_t6963/Makefile
git add AVR_t6963/ProMiniPinout.txt
git add AVR_t6963/spi.c
git add AVR_t6963/t6963.h
git add AVR_t6963/avrdude.conf
git add AVR_t6963/macros.h
git add AVR_t6963/pinDefines.h
git add AVR_t6963/run-avrdude
git add AVR_t6963/spi.h
git add AVR_t6963/USART.c
git add AVR_t6963/main.c
git add AVR_t6963/portpins.h
git add AVR_t6963/sfr_helper.h
git add AVR_t6963/t6963.c
git add AVR_t6963/USART.h

git add Truck_App1/Multi-Byte.vhd
git add Truck_App1/multi-byte.ucf
git add Truck_App1/multi-byte.xise
git add Truck_App1/Frequency.vhd
git add Truck_App1/period.vhd
git add Truck_App1/mod_m.vhd
git add Truck_App1/div.vhd
git add Truck_App1/bcd.vhd
git add Truck_App1/debounce.vhd
git add Truck_App1/3S500E_layout_bottom.txt
git add Truck_App1/3S500E_pin_assign.ods
git add Truck_App1/uartLED.vhd
git add Truck_App1/sendcharLED.vhd
git add Truck_App1/uartLED.vhd
git add Truck_App1/uartLED2.vhd
git add Truck_App1/uart_tx.vhd
git add Truck_App1/uart_rx.vhd
git add Truck_App1/rpm.ods
git add Truck_App1/sensor.vhd
git add Truck_App1/wrapperLED.vhd
git add Truck_App1/spi_slave.vhd
git add Truck_App1/spi_master.vhd
git add Truck_App1/test_uart/test_uart.vhd
git add Truck_App1/test_uart/test_uart.xise
git add Truck_App1/test_uart/test_uart.ucf
git add Truck_App1/test_rpm_mph.c
git add Truck_App1/test_write.c
git add Truck_App1/lib/*

git add PIC24_support/lib/*
git add PIC24_support/esos/*
git add PIC24_support/esos1/Truck_App2.c
git add PIC24_support/esos1/Truck_App.h
git add PIC24_support/PIC24FJ_pinlist.ods
git add PIC24_support/PIC24_board_pinout.txt
git add PIC24_support/esos1/esos1_notes.txt
git add PIC24_support/esos1/copy.sh
git add PIC24_support/esos1/extract.sh
git add PIC24_support/esos1/make_avr
git add PIC24_support/esos1/sim_read2.c

git add thread_io/ioports.c
git add thread_io/Makefile
git add thread_io/sched.c
git add thread_io/ioports.h
git add thread_io/tasks.c
git add thread_io/tasks.h
git add thread_io/lcd_func.c
git add thread_io/lcd_func.h
git add thread_io/queue/rdwr.h
git add thread_io/queue/rdwr.c
git add thread_io/queue/illist_threads_rw.h
git add thread_io/queue/illist_threads_rw.c
git add thread_io/queue/ollist_threads_rw.h
git add thread_io/queue/ollist_threads_rw.c
git add thread_io/ncurses/client.c
git add thread_io/ncurses/client.h
git add thread_io/linux_make
git add thread_io/make_db
git add thread_io/serial_io.c
git add thread_io/serial_io.h
git add thread_io/mytypes.h
git add thread_io/ncurses/demo_menus2.c
git add thread_io/ncurses/menu_scroll2.c
git add thread_io/ncurses/menu_scroll3.c
git add thread_io/ncurses/Makefile
git add thread_io/ncurses/init_db.c
git add thread_io/ncurses/list_db.c
git add thread_io/ncurses/make_db
git add thread_io/ncurses/setiodata.h
git add thread_io/ncurses/tcp_win.c
git add thread_io/ncurses/config_file.c
git add thread_io/ncurses/config_file.h
git add thread_io/ncurses/file_win.c
git add thread_io/ncurses/file_menu2.c
git add thread_io/ncurses/demo_forms4.c
git add thread_io/ncurses/form_supplement.c
git add thread_io/ncurses/form_sup.h
git add thread_io/ncurses/forms.sh
git add thread_io/ncurses/test.priv.h
git add thread_io/ncurses/text_entry.c
git add thread_io/ncurses/text_entry.h
git add thread_io/ncurses/ncurses_cfg.h
git add thread_io/thread_io_notes.txt
git add thread_io/dmake4
git add thread_io/mingetty/*
git add thread_io/test_tcp/*.c
git add thread_io/test_tcp/*.h
git add thread_io/test_tcp/iostate.bin
git add thread_io/test_tcp/make_target
git add thread_io/test_tcp/Makefile
git add thread_io/test_tcp/Makefile2

git status
git log --oneline > oneline.txt

