#ifndef MYTPYES_H
#define MYTPYES_H

typedef unsigned char UCHAR;
typedef unsigned int UINT;
typedef UCHAR* PUCHAR;
typedef unsigned long ULONG;

//#define TIME_DELAY 000000000
#define TIME_DELAY   990000000L

// this is the same as NUM_PORT_BITS (should be...)
#define NUM_DATA_RECS 40

#define NUM_DAT_NAMES 45
#define DAT_NAME_STR_LEN 25
//#define TDATE_STAMP_STR_LEN 25
#define TDATE_STAMP_STR_LEN 16
#define UPLOAD_BUFF_SIZE 10000
#define NUM_ADC_CHANNELS 4

// tcp command sent to TS-7200 from laptop
// these have to exactly match what's in cmd_array[] in tasks.c
enum cmd_types
{
	ENABLE_START = 1,
	STARTER_OFF,
	ON_ACC,
	OFF_ACC,
	ON_FUEL_PUMP,
	OFF_FUEL_PUMP,
	ON_FAN,
	OFF_FAN,
	START_SEQ,
	SHUTDOWN,
	SEND_IDATA,
	SEND_ODATA,
	EDIT_IDATA,
	EDIT_ODATA,
	EDIT_IDATA2,
	EDIT_ODATA2,
	SEND_ALL_IDATA,
	SEND_ALL_ODATA,
	RECV_ALL_IDATA,
	RECV_ALL_ODATA,
	SHOW_IDATA,
	SHOW_ODATA,
	SEND_SERIAL,
	CLOSE_SOCKET,
	CLEAR_SCREEN,
	SAVE_TO_DISK,
	TOGGLE_OUTPUTS,
	GET_DIR,
	LCD_SHIFT_RIGHT,
	LCD_SHIFT_LEFT,
	SCROLL_UP,
	SCROLL_DOWN,
	ENABLE_LCD,
	SET_TIME,
	GET_TIME,
	TCP_WINDOW_ON,
	TCP_WINDOW_OFF,
	LIVE_WINDOW_ON,
	LIVE_WINDOW_OFF,
	TEST_WRITE_FILE,
	TEST_IOPORT,
	TEST_IOPORT2,
	TOTAL_UP_TIME,
	UPLOAD_NEW,
	DONE_PROGRAM,
	EXIT_PROGRAM
}CMD_TYPES;

typedef struct
{
	int cmd;
	char cmd_str[20];
} CMD_STRUCT;

// msg's sent from PIC24 to TS-7200
enum upstream_msg
{
	RT_DATA = 0x21,
	ABLE_TO_START,
	RPM_OK,
	RPM_TO_LOW,
	RPM_TO_HIGH,
	OIL_PRESS_TOO_LOW,
	ENGINE_TEMP_TOO_HIGH
} UPSTREAM_MSG;

// msg's sent from TS-7200 to PIC24
enum downstream_msg
{
	COMM_CMD = 0x21,
	RE_ENTER_PASSWORD,
	TEST1,
	TEST2
} DOWNSTREAM_MSG;

enum output_types
{
	STARTER,
	ACCON,
	COOLINGFAN,
	FUELPUMP,
	PRELUBE,
	HEADLAMP,
	BRIGHTS,
	LEFTBLINKER,
	RIGHTBLINKER,
	RUNNINGLIGHTS,
	ALARMSPEAKER,
	ALARMLIGHT,
	BATTERYCHARGERELAY,
	DASHHEATER,
	BATTERYCOMPHEATER,
	CRANKCASEHEATER,
	TRAILERBRAKES,
	TRAILERLEFTBLINKER,
	TRAILERRIGHTBLINKER,
	INTRUDERALARM,
	DOMELIGHT,
	LIGHTBAR,
	BLINKINDICATE,
	BRAKELIGHTS,
	BACKUPLIGHTS
}OUTPUT_TYPES;

#define CHAR_CMD			2
#define GOTO_CMD			3
#define SET_MODE_CMD	 		4
#define LCD_CLRSCR			5
#define LCD_MSG1			6
#define BURN_EEPROM			7	// these are used by the eeprom/burn_main.c program
#define READ_EEPROM			8
#define PUT_STRING			9
#define PUT_STR				9
#define SEND_BYTE_RT_VALUES		10
#define SEND_INT_RT_VALUES		11

#endif
